name: My first workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: say hello
        run: echo "Hello World github action from ${{github.repository}}"

